<?php

if (!defined('WHATSAPP_VERIFY_TOKEN')) {
    define('WHATSAPP_VERIFY_TOKEN', 'EAHZBQNCMDlDkBRuAFZB3UfrF8QAAfzmVvbnPmvvFVxMylFkKA73dZAT4oDwJlfLxstHi9MfHsQmwMK2CAhuSKovhJJPsgtG2ZCDZCfg7V2eLjfpJRRZAznHc8iPMRKDllgLRZAGnZB7OBdOTJkpkZA5WiaCXZCxjRmRoMzI5BdWWyx8cp8rtZASKTeU8rZAWZAsWRgNUiLTZBYqoweThwPcsMjs5rRMOKwR5TIc6AB7GY8vBEXrFKbzbrZBf0SIeVHNfhIJkRQw83V836Cy82bmTEggQlNb');
}

if (!defined('WHATSAPP_ACCESS_TOKEN')) {
    define('WHATSAPP_ACCESS_TOKEN', 'EAHZBQNCMDlDkBRuAFZB3UfrF8QAAfzmVvbnPmvvFVxMylFkKA73dZAT4oDwJlfLxstHi9MfHsQmwMK2CAhuSKovhJJPsgtG2ZCDZCfg7V2eLjfpJRRZAznHc8iPMRKDllgLRZAGnZB7OBdOTJkpkZA5WiaCXZCxjRmRoMzI5BdWWyx8cp8rtZASKTeU8rZAWZAsWRgNUiLTZBYqoweThwPcsMjs5rRMOKwR5TIc6AB7GY8vBEXrFKbzbrZBf0SIeVHNfhIJkRQw83V836Cy82bmTEggQlNb');
}

if (!defined('WHATSAPP_PHONE_NUMBER_ID')) {
    define('WHATSAPP_PHONE_NUMBER_ID', '1104776422722447');
}

if (!defined('WHATSAPP_API_VERSION')) {
    define('WHATSAPP_API_VERSION', 'v25.0');
}
