<?php

if (!defined('WHATSAPP_VERIFY_TOKEN')) {
    define('WHATSAPP_VERIFY_TOKEN', 'EAHZBQNCMDlDkBRnsCh1yDOapF0mDZAB7JJpO8AwK8MDZBEzV1ODvHG0jKSEfqgqw8nt0inKu3ZBm0pLGuoFbWaKQ2JtBpLz4ROVIQEuiZBXqZA3KetXNuOi1pzm38tNFexAaOSOQE3uy0MzsRiDCXNdlTCsM6K1AGhZBWZBlYQhr9o7IcEFc2cSguTYlHw5mxgZDZD');
}

if (!defined('WHATSAPP_ACCESS_TOKEN')) {
    define('WHATSAPP_ACCESS_TOKEN', 'EAHZBQNCMDlDkBRnsCh1yDOapF0mDZAB7JJpO8AwK8MDZBEzV1ODvHG0jKSEfqgqw8nt0inKu3ZBm0pLGuoFbWaKQ2JtBpLz4ROVIQEuiZBXqZA3KetXNuOi1pzm38tNFexAaOSOQE3uy0MzsRiDCXNdlTCsM6K1AGhZBWZBlYQhr9o7IcEFc2cSguTYlHw5mxgZDZD');
}

if (!defined('WHATSAPP_PHONE_NUMBER_ID')) {
    define('WHATSAPP_PHONE_NUMBER_ID', '1104776422722447');
}

if (!defined('WHATSAPP_API_VERSION')) {
    define('WHATSAPP_API_VERSION', 'v25.0');
}

if (!defined('WHATSAPP_AUTO_REPLY_ENABLED')) {
    define('WHATSAPP_AUTO_REPLY_ENABLED', true);
}
