<?php
include_once MODEL . 'PayoutTransaction.php';
$model = ohnous_table_exists('payout_transactions') ? new PayoutTransaction($bdd) : null;
$row = $model ? $model->findById((int)($_GET['id']??0)) : null;
if(!$row){http_response_code(404);echo '<main class="admin-shell"><p>PayOut introuvable.</p></main>';return;}
$history = $model->getStatusHistory((int)$row['id']);
$debugEnabled = !empty((include CONFIG . 'payment.php')['freshpay']['payout']['debug']);
$statusDebug = null;$callbackReceived = null;$callbackDecrypted = null;
foreach($history as $event){$eventPayload=json_decode((string)($event['payload']??''),true);if($event['source']==='status_api'&&is_array($eventPayload)){$statusDebug=$eventPayload;}if($event['source']==='callback'&&is_array($eventPayload)){$callbackReceived=$eventPayload['received']??null;$callbackDecrypted=$eventPayload['decrypted']??null;}}
$labels=['pending'=>'En attente','submitted'=>'Soumis','processing'=>'En attente','success'=>'Réussi','successful'=>'Réussi','paid'=>'Réussi','completed'=>'Réussi','failed'=>'Échoué','error'=>'Échoué','expired'=>'Expiré','cancelled'=>'Annulé','canceled'=>'Annulé'];
$operators=['airtel'=>'Airtel Money','orange'=>'Orange Money','mpesa'=>'M-Pesa','afrimoney'=>'Afrimoney'];
$status=strtolower((string)$row['status']);$label=$labels[$status]??ucfirst($status);
$chartLabels=[];$chartValues=[];foreach($history as $index=>$event){$chartLabels[]=date('d/m H:i',strtotime($event['created_at']));$chartValues[]=$index+1;}
if(!$history){$chartLabels=[date('d/m H:i',strtotime($row['created_at']))];$chartValues=[1];}
?>
<main class="admin-shell admin-detail-page"><a class="admin-back-link" href="/admin-payouts"><i class="fa-solid fa-arrow-left"></i> Retour à l’historique</a><?= ohnous_render_admin_nav('payouts') ?><section class="admin-detail-heading"><div><span class="admin-hero__eyebrow">Détail PayOut</span><h1><?= htmlspecialchars($row['reference'],ENT_QUOTES,'UTF-8') ?></h1></div><span class="payment-status payment-status--<?= htmlspecialchars($status,ENT_QUOTES,'UTF-8') ?>"><?= htmlspecialchars($label,ENT_QUOTES,'UTF-8') ?></span></section>
<div class="admin-detail-grid"><section class="admin-detail-card"><h2>Transaction</h2><dl class="admin-detail-list"><div><dt>Bénéficiaire</dt><dd><?= htmlspecialchars($row['beneficiary']?:'—',ENT_QUOTES,'UTF-8') ?></dd></div><div><dt>Numéro international</dt><dd><?= htmlspecialchars($row['phone_number'],ENT_QUOTES,'UTF-8') ?></dd></div><div><dt>Opérateur</dt><dd><?= htmlspecialchars($operators[$row['operator']]??$row['operator'],ENT_QUOTES,'UTF-8') ?></dd></div><div><dt>Montant</dt><dd><?= number_format((float)$row['amount'],2,',',' ') ?> <?= htmlspecialchars($row['currency'],ENT_QUOTES,'UTF-8') ?></dd></div><div><dt>Motif</dt><dd><?= htmlspecialchars($row['reason'],ENT_QUOTES,'UTF-8') ?></dd></div><div><dt>Administrateur</dt><dd><?= htmlspecialchars($row['admin_name']?:'—',ENT_QUOTES,'UTF-8') ?></dd></div><div><dt>Créé le</dt><dd><?= htmlspecialchars($row['created_at'],ENT_QUOTES,'UTF-8') ?></dd></div><div><dt>Mis à jour le</dt><dd><?= htmlspecialchars($row['updated_at'],ENT_QUOTES,'UTF-8') ?></dd></div></dl></section>
<section class="admin-detail-card"><h2>Références FreshPay</h2><dl class="admin-detail-list"><div><dt>Référence interne</dt><dd><?= htmlspecialchars($row['reference'],ENT_QUOTES,'UTF-8') ?></dd></div><div><dt>Référence FreshPay</dt><dd><?= htmlspecialchars($row['freshpay_reference']?:'—',ENT_QUOTES,'UTF-8') ?></dd></div><div><dt>Référence opérateur</dt><dd><?= htmlspecialchars($row['operator_reference']?:'—',ENT_QUOTES,'UTF-8') ?></dd></div><div><dt>ID transaction</dt><dd><?= htmlspecialchars($row['transaction_id']?:'—',ENT_QUOTES,'UTF-8') ?></dd></div><div><dt>Message</dt><dd><?= htmlspecialchars($row['status_description']?:'—',ENT_QUOTES,'UTF-8') ?></dd></div><div><dt>Erreur détaillée</dt><dd><?= htmlspecialchars($row['error_detail']?:'—',ENT_QUOTES,'UTF-8') ?></dd></div></dl><button class="btn_ohnous" id="payout_refresh" data-reference="<?= htmlspecialchars($row['reference'],ENT_QUOTES,'UTF-8') ?>"><i class="fa-solid fa-rotate"></i> Actualiser</button></section>
<section class="admin-detail-card admin-detail-card--wide"><h2>Évolution de la transaction</h2><div id="payout_status_chart" class="admin-chart"></div><ol class="transaction-timeline"><?php foreach($history as $event): ?><li><span><strong><?= htmlspecialchars($labels[strtolower($event['status'])]??ucfirst($event['status']),ENT_QUOTES,'UTF-8') ?></strong><br><?= htmlspecialchars($event['description']?:'—',ENT_QUOTES,'UTF-8') ?> <small>(<?= htmlspecialchars($event['source'],ENT_QUOTES,'UTF-8') ?>)</small></span><span><?= htmlspecialchars($event['created_at'],ENT_QUOTES,'UTF-8') ?></span></li><?php endforeach ?></ol></section>
<section class="admin-detail-card admin-detail-card--wide"><h2>Réponse FreshPay</h2><pre class="payout-json"><?= htmlspecialchars(json_encode(json_decode((string)$row['response_payload'],true) ?: $row['response_payload'],JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),ENT_QUOTES,'UTF-8') ?></pre></section>
<section class="admin-detail-card admin-detail-card--wide"><h2>Échanges FreshPay complets</h2><?php foreach($history as $event): $payload=json_decode((string)($event['payload']??''),true); if(!$payload) continue; ?><h3><?= htmlspecialchars($event['source'].' — '.$event['created_at'],ENT_QUOTES,'UTF-8') ?></h3><pre class="payout-json"><?= htmlspecialchars(json_encode($payload,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),ENT_QUOTES,'UTF-8') ?></pre><?php endforeach ?></section>
<?php if($debugEnabled): ?><section class="admin-detail-card admin-detail-card--wide"><h2>Débogage FreshPay</h2><h3>Requête PayOut</h3><pre class="payout-json"><?= htmlspecialchars(json_encode(json_decode((string)$row['request_payload'],true) ?: $row['request_payload'],JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),ENT_QUOTES,'UTF-8') ?></pre><h3>Requête et réponse Check Status</h3><pre class="payout-json"><?= htmlspecialchars(json_encode($statusDebug,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),ENT_QUOTES,'UTF-8') ?></pre><h3>Callback reçu</h3><pre class="payout-json"><?= htmlspecialchars(json_encode($callbackReceived,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),ENT_QUOTES,'UTF-8') ?></pre><h3>Callback déchiffré</h3><pre class="payout-json"><?= htmlspecialchars(json_encode($callbackDecrypted,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),ENT_QUOTES,'UTF-8') ?></pre></section><?php endif ?></div></main>
<script>window.ohnousPayoutDetail=<?= json_encode(['status'=>$label,'labels'=>$chartLabels,'values'=>$chartValues],JSON_UNESCAPED_UNICODE) ?>;</script><script src="/node_modules/apexcharts/dist/apexcharts.min.js"></script><script src="/asset/js/admin_payout_detail.js" defer></script>
