<?php
include_once MODEL . 'PayoutTransaction.php';
$exists=ohnous_table_exists('payout_transactions'); $model=$exists?new PayoutTransaction($bdd):null;
$filters=['q'=>trim((string)($_GET['q']??'')),'status'=>trim((string)($_GET['status']??'')),'operator'=>trim((string)($_GET['operator']??'')),'date_from'=>trim((string)($_GET['date_from']??'')),'date_to'=>trim((string)($_GET['date_to']??''))]; $rows=$model?$model->search($filters,100):[];
$labels=['pending'=>'En attente','submitted'=>'Soumis','processing'=>'En cours','success'=>'Réussi','successful'=>'Réussi','failed'=>'Échoué','error'=>'Échoué','expired'=>'Expiré','cancelled'=>'Annulé','refunded'=>'Remboursé'];
?>
<main class="admin-shell admin-payment-page"><section class="admin-hero liquid-panel"><div><span class="admin-hero__eyebrow">PayOut</span><h1>Historique des PayOut</h1><p>Suivez les transferts Mobile Money FreshPay.</p></div><a class="btn_ohnous" href="/admin-payout"><i class="fa-solid fa-plus"></i> Nouveau PayOut</a></section><?= ohnous_render_admin_nav('payouts') ?>
<?php if(!$exists): ?><div class="admin-notice">Appliquez la migration SQL documentée dans le README.md.</div><?php else: ?>
<form class="admin-search-bar admin-payment-filters liquid-panel" method="get"><input type="search" name="q" value="<?= htmlspecialchars($filters['q'],ENT_QUOTES,'UTF-8') ?>" placeholder="Référence, bénéficiaire ou numéro"><select name="status"><option value="">Tous les statuts</option><?php foreach($labels as $key=>$label): ?><option value="<?= $key ?>" <?= $filters['status']===$key?'selected':'' ?>><?= $label ?></option><?php endforeach ?></select><select name="operator"><option value="">Tous les opérateurs</option><?php foreach(['airtel'=>'Airtel','orange'=>'Orange','mpesa'=>'M-Pesa','afrimoney'=>'Afrimoney'] as $key=>$label): ?><option value="<?= $key ?>" <?= $filters['operator']===$key?'selected':'' ?>><?= $label ?></option><?php endforeach ?></select><input type="date" name="date_from" value="<?= htmlspecialchars($filters['date_from'],ENT_QUOTES,'UTF-8') ?>"><input type="date" name="date_to" value="<?= htmlspecialchars($filters['date_to'],ENT_QUOTES,'UTF-8') ?>"><button class="btn_ohnous" type="submit"><i class="fa-solid fa-filter"></i> Filtrer</button></form>
<section class="admin-data-table liquid-panel"><table><thead><tr><th>Référence</th><th>Bénéficiaire</th><th>Numéro</th><th>Opérateur</th><th class="is-number">Montant</th><th>Statut</th><th>Date</th><th>Référence FreshPay</th><th>Actions</th></tr></thead><tbody><?php if(!$rows): ?><tr><td colspan="9" class="admin-table-empty">Aucun PayOut trouvé.</td></tr><?php endif ?><?php foreach($rows as $row): $status=strtolower((string)$row['status']); ?><tr><td data-label="Référence"><strong><?= htmlspecialchars($row['reference'],ENT_QUOTES,'UTF-8') ?></strong></td><td data-label="Bénéficiaire"><?= htmlspecialchars($row['beneficiary']?:'—',ENT_QUOTES,'UTF-8') ?></td><td data-label="Numéro"><?= htmlspecialchars($row['phone_number'],ENT_QUOTES,'UTF-8') ?></td><td data-label="Opérateur"><?= htmlspecialchars(ucfirst($row['operator']),ENT_QUOTES,'UTF-8') ?></td><td data-label="Montant" class="is-number"><?= number_format((float)$row['amount'],2,',',' ') ?> <?= htmlspecialchars($row['currency'],ENT_QUOTES,'UTF-8') ?></td><td data-label="Statut"><span class="payment-status payment-status--<?= htmlspecialchars($status,ENT_QUOTES,'UTF-8') ?>"><?= htmlspecialchars($labels[$status]??ucfirst($status),ENT_QUOTES,'UTF-8') ?></span></td><td data-label="Date"><?= htmlspecialchars($row['created_at'],ENT_QUOTES,'UTF-8') ?></td><td data-label="Référence FreshPay"><?= htmlspecialchars($row['freshpay_reference']?:'—',ENT_QUOTES,'UTF-8') ?></td><td data-label="Actions"><a class="admin-table-action" href="/admin-payout-details?id=<?= (int)$row['id'] ?>"><i class="fa-solid fa-eye"></i><span>Voir les détails</span></a></td></tr><?php endforeach ?></tbody></table></section><?php endif ?></main>
