<?php
include_once MODEL . 'PayoutTransaction.php';
$row=ohnous_table_exists('payout_transactions')?(new PayoutTransaction($bdd))->findById((int)($_GET['id']??0)):null;
if(!$row){http_response_code(404);echo '<main class="admin-shell"><p>PayOut introuvable.</p></main>';return;}
$labels=['pending'=>'En attente','submitted'=>'Soumis','processing'=>'En cours','success'=>'Réussi','successful'=>'Réussi','failed'=>'Échoué','error'=>'Échoué','expired'=>'Expiré','cancelled'=>'Annulé','refunded'=>'Remboursé'];$status=strtolower((string)$row['status']);$label=$labels[$status]??ucfirst($status);
?>
<main class="admin-shell admin-detail-page"><a class="admin-back-link" href="/admin-payouts"><i class="fa-solid fa-arrow-left"></i> Retour à l’historique des PayOut</a><section class="admin-detail-heading"><div><span class="admin-hero__eyebrow">PayOut</span><h1><?= htmlspecialchars($row['reference'],ENT_QUOTES,'UTF-8') ?></h1></div><span class="payment-status payment-status--<?= htmlspecialchars($status,ENT_QUOTES,'UTF-8') ?>"><?= htmlspecialchars($label,ENT_QUOTES,'UTF-8') ?></span></section>
<div class="admin-detail-grid"><section class="admin-detail-card"><h2>Informations du transfert</h2><dl class="admin-detail-list"><div><dt>Bénéficiaire</dt><dd><?= htmlspecialchars($row['beneficiary']?:'—',ENT_QUOTES,'UTF-8') ?></dd></div><div><dt>Numéro</dt><dd><?= htmlspecialchars($row['phone_number'],ENT_QUOTES,'UTF-8') ?></dd></div><div><dt>Opérateur</dt><dd><?= htmlspecialchars(ucfirst($row['operator']),ENT_QUOTES,'UTF-8') ?></dd></div><div><dt>Montant</dt><dd><?= number_format((float)$row['amount'],2,',',' ') ?> <?= htmlspecialchars($row['currency'],ENT_QUOTES,'UTF-8') ?></dd></div><div><dt>Motif</dt><dd><?= htmlspecialchars($row['reason'],ENT_QUOTES,'UTF-8') ?></dd></div><div><dt>Date</dt><dd><?= htmlspecialchars($row['created_at'],ENT_QUOTES,'UTF-8') ?></dd></div></dl></section>
<section class="admin-detail-card"><h2>Réponse FreshPay</h2><dl class="admin-detail-list"><div><dt>Référence interne</dt><dd><?= htmlspecialchars($row['reference'],ENT_QUOTES,'UTF-8') ?></dd></div><div><dt>Référence FreshPay</dt><dd><?= htmlspecialchars($row['freshpay_reference']?:'—',ENT_QUOTES,'UTF-8') ?></dd></div><div><dt>Transaction</dt><dd><?= htmlspecialchars($row['transaction_id']?:'—',ENT_QUOTES,'UTF-8') ?></dd></div><div><dt>Statut</dt><dd><?= htmlspecialchars($label,ENT_QUOTES,'UTF-8') ?></dd></div><div><dt>Message</dt><dd><?= htmlspecialchars($row['status_description']?:'—',ENT_QUOTES,'UTF-8') ?></dd></div></dl><button class="btn_ohnous" id="payout_refresh" data-reference="<?= htmlspecialchars($row['reference'],ENT_QUOTES,'UTF-8') ?>"><i class="fa-solid fa-rotate"></i> Actualiser le statut</button></section>
<section class="admin-detail-card admin-detail-card--wide"><h2>États du transfert</h2><div id="payout_status_chart" class="admin-chart"></div><ol class="transaction-timeline"><li><strong>PayOut créé</strong><span><?= htmlspecialchars($row['created_at'],ENT_QUOTES,'UTF-8') ?></span></li><li><strong><?= htmlspecialchars($label,ENT_QUOTES,'UTF-8') ?></strong><span><?= htmlspecialchars($row['updated_at'],ENT_QUOTES,'UTF-8') ?></span></li></ol></section></div></main>
<script>window.ohnousPayoutDetail=<?= json_encode(['status'=>$label],JSON_UNESCAPED_UNICODE) ?>;</script><script src="/node_modules/apexcharts/dist/apexcharts.min.js"></script><script src="/asset/js/admin_payout_detail.js" defer></script>
